name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # SDK Version to use.

    - name: Build project
      run: dotnet build HtmlPdfPlus.sln -c Release

    - name: Install Playwright browsers
      run: pwsh src/TestHtmlPdfCliPlus/bin/Release/net9.0/playwright.ps1 install --with-deps

    - name: Run test cases
      run: dotnet test -c Release --no-build
