name: Publish

on:
  push:
    tags: [ v* ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # SDK Version to use.

    - name: Setup Version
      id: setup_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    - name: Pack NuGet Package HtmlPdfPlus.Server
      run: dotnet pack src/HtmlPdfPlus.Server/HtmlPdfPlus.Server.csproj -c Release -o --use-current-runtime ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }}

    - name: Pack NuGet Package HtmlPdfPlus.Client
      run: dotnet pack src/HtmlPdfPlus.Client/HtmlPdfPlus.Client.csproj -c Release -o --use-current-runtime ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }}

    - name: Publish  Package HtmlPdfPlus.Server and HtmlPdfPlus.Client
      run: dotnet nuget push dist/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
